# Generated by Django 4.0.4 on 2022-06-09 09:06

import datetime
import django.core.validators
from django.db import migrations, models
import driverlicense.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7, message='Car Numer must contain 7 symbol : NN000NN'), driverlicense.models.Cars.check_num])),
                ('color', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(help_text='Publish date', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('marck', models.CharField(max_length=25, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
