# Generated by Django 4.0.4 on 2022-06-09 09:09

import django.core.validators
from django.db import migrations, models
import driverlicense.models


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfid', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11, message='Card ID Length has to be contain 11 integer : ***********'), driverlicense.models.Person.only_int])),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('father', models.CharField(help_text="Father's name", max_length=150, null=True)),
                ('birth', models.DateField(help_text='Enter the date of birth', null=True)),
            ],
        ),
    ]
