# Generated by Django 4.0.4 on 2022-06-09 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import driverlicense.models


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='number',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(7, message='Car Numer must contain 7 symbol : NN000NN'), driverlicense.models.Cars.check_num]),
        ),
        migrations.AlterField(
            model_name='person',
            name='selfid',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Card ID Length has to be contain 11 integer : ***********'), driverlicense.models.Person.only_int]),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrol_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driverlicense.cars')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driverlicense.person')),
            ],
            options={
                'unique_together': {('person', 'car')},
            },
        ),
    ]
