# Generated by Django 4.0.4 on 2022-06-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0003_alter_cars_number_alter_person_selfid_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driverlicense.cars', unique=True),
        ),
    ]
