# Generated by Django 4.0.4 on 2022-06-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0004_alter_license_car'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together=set(),
        ),
    ]
