# Generated by Django 4.0.4 on 2022-06-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0005_alter_license_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrol_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ManyToManyField(to='driverlicense.cars')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driverlicense.person')),
            ],
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
