# Generated by Django 4.0.4 on 2022-06-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverlicense', '0006_cardriver_delete_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='car',
            field=models.ManyToManyField(blank=True, help_text='Choose if employeer has a car or cars', to='driverlicense.cars'),
        ),
        migrations.DeleteModel(
            name='CarDriver',
        ),
    ]
